
INSERT INTO public.nutrition_articles (title, slug, category, excerpt, content, cover_image_url) VALUES
('The Foundations of a Balanced Diet', 'foundations-balanced-diet', 'Basics',
 'A practical guide to building a nutritionally complete plate for every meal.',
 E'## What is a balanced diet?\n\nA balanced diet provides the right proportions of carbohydrates, proteins, fats, vitamins, minerals, and water to maintain health.\n\n### The plate method\n\n- **Half plate**: vegetables and fruits\n- **Quarter plate**: whole grains\n- **Quarter plate**: lean protein\n- **Side**: dairy or plant-based alternative\n\n### Tips\n\n1. Choose whole foods over processed.\n2. Stay hydrated — 8 glasses of water daily.\n3. Limit added sugar and sodium.',
 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=1200'),
('Iron-Rich Foods on a Budget', 'iron-rich-foods-budget', 'Micronutrients',
 'Affordable everyday foods that fight iron deficiency.',
 E'## Why iron matters\n\nIron carries oxygen in your blood. Deficiency causes fatigue and weakness.\n\n### Best budget sources\n\n- Spinach and leafy greens\n- Lentils and chickpeas\n- Jaggery (gur)\n- Pumpkin seeds\n- Eggs\n\nPair with vitamin C (lemon, amla) to boost absorption.',
 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=1200'),
('Nutritious Meals Under ₹100', 'nutritious-meals-under-100', 'Meal Planning',
 'Three filling, balanced meal ideas that cost less than ₹100.',
 E'## Khichdi with vegetables\nRice + moong dal + seasonal vegetables. Complete protein, easy to digest.\n\n## Chana chaat\nBoiled chickpeas, onion, tomato, lemon. High protein, high fiber.\n\n## Vegetable poha\nFlattened rice with peas, carrots, peanuts. Quick and balanced.',
 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=1200'),
('Protein Needs Explained', 'protein-needs-explained', 'Macronutrients',
 'How much protein do you actually need each day?',
 E'## Daily requirement\n\nAdults need roughly **0.8 g per kg** of body weight per day.\n\n### Plant sources\n- Lentils, beans, soy\n- Nuts, seeds\n- Quinoa, oats\n\n### Animal sources\n- Eggs, dairy, fish, poultry',
 'https://images.unsplash.com/photo-1607532941433-304659e8198a?w=1200'),
('Healthy Eating for Children', 'healthy-eating-children', 'Family',
 'Helping kids develop lifelong healthy habits.',
 E'## Key nutrients for growing kids\n\n- Calcium for bones\n- Iron for energy\n- Protein for growth\n- Healthy fats for brain development\n\n### Practical tips\n- Eat together as a family\n- Limit sugary drinks\n- Make veggies fun and colorful',
 'https://images.unsplash.com/photo-1502301103665-0b95cc738daf?w=1200'),
('Reducing Food Waste at Home', 'reducing-food-waste-home', 'Sustainability',
 'Simple habits that save food and money.',
 E'## Plan, store, share\n\n1. Plan meals before you shop\n2. Store produce correctly\n3. Use leftovers creatively\n4. Donate surplus food via our platform',
 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=1200');
